//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  import type { TinaMarkdownContent } from 'tinacms/dist/rich-text';
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
  /** A rich-text document, renderable by TinaMarkdown */
  RichText: { input: TinaMarkdownContent; output: TinaMarkdownContent; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  page: Page;
  pageConnection: PageConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};

export type DocumentFilter = {
  page?: InputMaybe<PageFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Page | Folder;

export type PageHero = {
  __typename?: 'PageHero';
  badge?: Maybe<Scalars['String']['output']>;
  headline: Scalars['String']['output'];
  subheading?: Maybe<Scalars['String']['output']>;
  availabilityNotice: Scalars['String']['output'];
};

export type PageServicesServicesListExamples = {
  __typename?: 'PageServicesServicesListExamples';
  image?: Maybe<Scalars['String']['output']>;
  styleLabel?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type PageServicesServicesList = {
  __typename?: 'PageServicesServicesList';
  name: Scalars['String']['output'];
  price: Scalars['String']['output'];
  duration?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  deliverables?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  examples?: Maybe<Array<Maybe<PageServicesServicesListExamples>>>;
  id: Scalars['String']['output'];
  calSlug?: Maybe<Scalars['String']['output']>;
};

export type PageServices = {
  __typename?: 'PageServices';
  sectionTitle?: Maybe<Scalars['String']['output']>;
  pricingNote?: Maybe<Scalars['String']['output']>;
  servicesList?: Maybe<Array<Maybe<PageServicesServicesList>>>;
};

export type PagePortfolioPortfolioList = {
  __typename?: 'PagePortfolioPortfolioList';
  title?: Maybe<Scalars['String']['output']>;
  id: Scalars['String']['output'];
  image: Scalars['String']['output'];
  alt: Scalars['String']['output'];
  tag?: Maybe<Scalars['String']['output']>;
  images?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type PagePortfolio = {
  __typename?: 'PagePortfolio';
  heroImage?: Maybe<Scalars['String']['output']>;
  ogImage?: Maybe<Scalars['String']['output']>;
  ogImageAlt?: Maybe<Scalars['String']['output']>;
  portfolioList?: Maybe<Array<Maybe<PagePortfolioPortfolioList>>>;
};

export type PageFaqFaqList = {
  __typename?: 'PageFaqFaqList';
  question: Scalars['String']['output'];
  answer: Scalars['String']['output'];
};

export type PageFaq = {
  __typename?: 'PageFaq';
  sectionTitle?: Maybe<Scalars['String']['output']>;
  sectionSubtitle?: Maybe<Scalars['String']['output']>;
  faqList?: Maybe<Array<Maybe<PageFaqFaqList>>>;
};

export type PageEventsFormFieldsInputField = {
  __typename?: 'PageEventsFormFieldsInputField';
  label: Scalars['String']['output'];
  fieldType?: Maybe<Scalars['String']['output']>;
  placeholder?: Maybe<Scalars['String']['output']>;
  required?: Maybe<Scalars['Boolean']['output']>;
};

export type PageEventsFormFieldsSelectField = {
  __typename?: 'PageEventsFormFieldsSelectField';
  label: Scalars['String']['output'];
  options?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  required?: Maybe<Scalars['Boolean']['output']>;
};

export type PageEventsFormFieldsTextareaField = {
  __typename?: 'PageEventsFormFieldsTextareaField';
  label: Scalars['String']['output'];
  placeholder?: Maybe<Scalars['String']['output']>;
  required?: Maybe<Scalars['Boolean']['output']>;
};

export type PageEventsFormFields = PageEventsFormFieldsInputField | PageEventsFormFieldsSelectField | PageEventsFormFieldsTextareaField;

export type PageEventsFormOptions = {
  __typename?: 'PageEventsFormOptions';
  submitButtonText?: Maybe<Scalars['String']['output']>;
};

export type PageEvents = {
  __typename?: 'PageEvents';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  showForm?: Maybe<Scalars['Boolean']['output']>;
  formFields?: Maybe<Array<Maybe<PageEventsFormFields>>>;
  formOptions?: Maybe<PageEventsFormOptions>;
};

export type PageSiteAddress = {
  __typename?: 'PageSiteAddress';
  locality?: Maybe<Scalars['String']['output']>;
  region?: Maybe<Scalars['String']['output']>;
  country?: Maybe<Scalars['String']['output']>;
};

export type PageSiteGeo = {
  __typename?: 'PageSiteGeo';
  latitude?: Maybe<Scalars['Float']['output']>;
  longitude?: Maybe<Scalars['Float']['output']>;
};

export type PageSiteOpeningHours = {
  __typename?: 'PageSiteOpeningHours';
  opens?: Maybe<Scalars['String']['output']>;
  closes?: Maybe<Scalars['String']['output']>;
};

export type PageSite = {
  __typename?: 'PageSite';
  studioName: Scalars['String']['output'];
  stylistName: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  keywords?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  email?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  instagramHandle?: Maybe<Scalars['String']['output']>;
  locationDisplay?: Maybe<Scalars['String']['output']>;
  calUsername?: Maybe<Scalars['String']['output']>;
  calDefaultSlug?: Maybe<Scalars['String']['output']>;
  address?: Maybe<PageSiteAddress>;
  geo?: Maybe<PageSiteGeo>;
  areaServed?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  openingDays?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  openingHours?: Maybe<PageSiteOpeningHours>;
  priceRange?: Maybe<Scalars['String']['output']>;
};

export type Page = Node & Document & {
  __typename?: 'Page';
  hero?: Maybe<PageHero>;
  services?: Maybe<PageServices>;
  portfolio?: Maybe<PagePortfolio>;
  faq?: Maybe<PageFaq>;
  events?: Maybe<PageEvents>;
  site?: Maybe<PageSite>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PageHeroFilter = {
  badge?: InputMaybe<StringFilter>;
  headline?: InputMaybe<StringFilter>;
  subheading?: InputMaybe<StringFilter>;
  availabilityNotice?: InputMaybe<StringFilter>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PageServicesServicesListExamplesFilter = {
  image?: InputMaybe<ImageFilter>;
  styleLabel?: InputMaybe<StringFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type PageServicesServicesListFilter = {
  name?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  duration?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  deliverables?: InputMaybe<StringFilter>;
  examples?: InputMaybe<PageServicesServicesListExamplesFilter>;
  id?: InputMaybe<StringFilter>;
  calSlug?: InputMaybe<StringFilter>;
};

export type PageServicesFilter = {
  sectionTitle?: InputMaybe<StringFilter>;
  pricingNote?: InputMaybe<StringFilter>;
  servicesList?: InputMaybe<PageServicesServicesListFilter>;
};

export type PagePortfolioPortfolioListFilter = {
  title?: InputMaybe<StringFilter>;
  id?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  tag?: InputMaybe<StringFilter>;
  images?: InputMaybe<ImageFilter>;
};

export type PagePortfolioFilter = {
  heroImage?: InputMaybe<ImageFilter>;
  ogImage?: InputMaybe<ImageFilter>;
  ogImageAlt?: InputMaybe<StringFilter>;
  portfolioList?: InputMaybe<PagePortfolioPortfolioListFilter>;
};

export type PageFaqFaqListFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type PageFaqFilter = {
  sectionTitle?: InputMaybe<StringFilter>;
  sectionSubtitle?: InputMaybe<StringFilter>;
  faqList?: InputMaybe<PageFaqFaqListFilter>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PageEventsFormFieldsInputFieldFilter = {
  label?: InputMaybe<StringFilter>;
  fieldType?: InputMaybe<StringFilter>;
  placeholder?: InputMaybe<StringFilter>;
  required?: InputMaybe<BooleanFilter>;
};

export type PageEventsFormFieldsSelectFieldFilter = {
  label?: InputMaybe<StringFilter>;
  options?: InputMaybe<StringFilter>;
  required?: InputMaybe<BooleanFilter>;
};

export type PageEventsFormFieldsTextareaFieldFilter = {
  label?: InputMaybe<StringFilter>;
  placeholder?: InputMaybe<StringFilter>;
  required?: InputMaybe<BooleanFilter>;
};

export type PageEventsFormFieldsFilter = {
  inputField?: InputMaybe<PageEventsFormFieldsInputFieldFilter>;
  selectField?: InputMaybe<PageEventsFormFieldsSelectFieldFilter>;
  textareaField?: InputMaybe<PageEventsFormFieldsTextareaFieldFilter>;
};

export type PageEventsFormOptionsFilter = {
  submitButtonText?: InputMaybe<StringFilter>;
};

export type PageEventsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  showForm?: InputMaybe<BooleanFilter>;
  formFields?: InputMaybe<PageEventsFormFieldsFilter>;
  formOptions?: InputMaybe<PageEventsFormOptionsFilter>;
};

export type PageSiteAddressFilter = {
  locality?: InputMaybe<StringFilter>;
  region?: InputMaybe<StringFilter>;
  country?: InputMaybe<StringFilter>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type PageSiteGeoFilter = {
  latitude?: InputMaybe<NumberFilter>;
  longitude?: InputMaybe<NumberFilter>;
};

export type PageSiteOpeningHoursFilter = {
  opens?: InputMaybe<StringFilter>;
  closes?: InputMaybe<StringFilter>;
};

export type PageSiteFilter = {
  studioName?: InputMaybe<StringFilter>;
  stylistName?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  keywords?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  instagramHandle?: InputMaybe<StringFilter>;
  locationDisplay?: InputMaybe<StringFilter>;
  calUsername?: InputMaybe<StringFilter>;
  calDefaultSlug?: InputMaybe<StringFilter>;
  address?: InputMaybe<PageSiteAddressFilter>;
  geo?: InputMaybe<PageSiteGeoFilter>;
  areaServed?: InputMaybe<StringFilter>;
  openingDays?: InputMaybe<StringFilter>;
  openingHours?: InputMaybe<PageSiteOpeningHoursFilter>;
  priceRange?: InputMaybe<StringFilter>;
};

export type PageFilter = {
  hero?: InputMaybe<PageHeroFilter>;
  services?: InputMaybe<PageServicesFilter>;
  portfolio?: InputMaybe<PagePortfolioFilter>;
  faq?: InputMaybe<PageFaqFilter>;
  events?: InputMaybe<PageEventsFilter>;
  site?: InputMaybe<PageSiteFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePage: Page;
  createPage: Page;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};

export type DocumentUpdateMutation = {
  page?: InputMaybe<PageMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  page?: InputMaybe<PageMutation>;
};

export type PageHeroMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  headline?: InputMaybe<Scalars['String']['input']>;
  subheading?: InputMaybe<Scalars['String']['input']>;
  availabilityNotice?: InputMaybe<Scalars['String']['input']>;
};

export type PageServicesServicesListExamplesMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  styleLabel?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type PageServicesServicesListMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  duration?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  deliverables?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  examples?: InputMaybe<Array<InputMaybe<PageServicesServicesListExamplesMutation>>>;
  id?: InputMaybe<Scalars['String']['input']>;
  calSlug?: InputMaybe<Scalars['String']['input']>;
};

export type PageServicesMutation = {
  sectionTitle?: InputMaybe<Scalars['String']['input']>;
  pricingNote?: InputMaybe<Scalars['String']['input']>;
  servicesList?: InputMaybe<Array<InputMaybe<PageServicesServicesListMutation>>>;
};

export type PagePortfolioPortfolioListMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  id?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  tag?: InputMaybe<Scalars['String']['input']>;
  images?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PagePortfolioMutation = {
  heroImage?: InputMaybe<Scalars['String']['input']>;
  ogImage?: InputMaybe<Scalars['String']['input']>;
  ogImageAlt?: InputMaybe<Scalars['String']['input']>;
  portfolioList?: InputMaybe<Array<InputMaybe<PagePortfolioPortfolioListMutation>>>;
};

export type PageFaqFaqListMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
};

export type PageFaqMutation = {
  sectionTitle?: InputMaybe<Scalars['String']['input']>;
  sectionSubtitle?: InputMaybe<Scalars['String']['input']>;
  faqList?: InputMaybe<Array<InputMaybe<PageFaqFaqListMutation>>>;
};

export type PageEventsFormFieldsInputFieldMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  fieldType?: InputMaybe<Scalars['String']['input']>;
  placeholder?: InputMaybe<Scalars['String']['input']>;
  required?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PageEventsFormFieldsSelectFieldMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  options?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  required?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PageEventsFormFieldsTextareaFieldMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  placeholder?: InputMaybe<Scalars['String']['input']>;
  required?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PageEventsFormFieldsMutation = {
  inputField?: InputMaybe<PageEventsFormFieldsInputFieldMutation>;
  selectField?: InputMaybe<PageEventsFormFieldsSelectFieldMutation>;
  textareaField?: InputMaybe<PageEventsFormFieldsTextareaFieldMutation>;
};

export type PageEventsFormOptionsMutation = {
  submitButtonText?: InputMaybe<Scalars['String']['input']>;
};

export type PageEventsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  showForm?: InputMaybe<Scalars['Boolean']['input']>;
  formFields?: InputMaybe<Array<InputMaybe<PageEventsFormFieldsMutation>>>;
  formOptions?: InputMaybe<PageEventsFormOptionsMutation>;
};

export type PageSiteAddressMutation = {
  locality?: InputMaybe<Scalars['String']['input']>;
  region?: InputMaybe<Scalars['String']['input']>;
  country?: InputMaybe<Scalars['String']['input']>;
};

export type PageSiteGeoMutation = {
  latitude?: InputMaybe<Scalars['Float']['input']>;
  longitude?: InputMaybe<Scalars['Float']['input']>;
};

export type PageSiteOpeningHoursMutation = {
  opens?: InputMaybe<Scalars['String']['input']>;
  closes?: InputMaybe<Scalars['String']['input']>;
};

export type PageSiteMutation = {
  studioName?: InputMaybe<Scalars['String']['input']>;
  stylistName?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  keywords?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  instagramHandle?: InputMaybe<Scalars['String']['input']>;
  locationDisplay?: InputMaybe<Scalars['String']['input']>;
  calUsername?: InputMaybe<Scalars['String']['input']>;
  calDefaultSlug?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<PageSiteAddressMutation>;
  geo?: InputMaybe<PageSiteGeoMutation>;
  areaServed?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  openingDays?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  openingHours?: InputMaybe<PageSiteOpeningHoursMutation>;
  priceRange?: InputMaybe<Scalars['String']['input']>;
};

export type PageMutation = {
  hero?: InputMaybe<PageHeroMutation>;
  services?: InputMaybe<PageServicesMutation>;
  portfolio?: InputMaybe<PagePortfolioMutation>;
  faq?: InputMaybe<PageFaqMutation>;
  events?: InputMaybe<PageEventsMutation>;
  site?: InputMaybe<PageSiteMutation>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type PageHeroFilter = {
  badge?: StringFilter | null | undefined;
  headline?: StringFilter | null | undefined;
  subheading?: StringFilter | null | undefined;
  availabilityNotice?: StringFilter | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type PageServicesServicesListExamplesFilter = {
  image?: ImageFilter | null | undefined;
  styleLabel?: StringFilter | null | undefined;
  alt?: StringFilter | null | undefined;
};

export type PageServicesServicesListFilter = {
  name?: StringFilter | null | undefined;
  price?: StringFilter | null | undefined;
  duration?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  deliverables?: StringFilter | null | undefined;
  examples?: PageServicesServicesListExamplesFilter | null | undefined;
  id?: StringFilter | null | undefined;
  calSlug?: StringFilter | null | undefined;
};

export type PageServicesFilter = {
  sectionTitle?: StringFilter | null | undefined;
  pricingNote?: StringFilter | null | undefined;
  servicesList?: PageServicesServicesListFilter | null | undefined;
};

export type PagePortfolioPortfolioListFilter = {
  title?: StringFilter | null | undefined;
  id?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  alt?: StringFilter | null | undefined;
  tag?: StringFilter | null | undefined;
  images?: ImageFilter | null | undefined;
};

export type PagePortfolioFilter = {
  heroImage?: ImageFilter | null | undefined;
  ogImage?: ImageFilter | null | undefined;
  ogImageAlt?: StringFilter | null | undefined;
  portfolioList?: PagePortfolioPortfolioListFilter | null | undefined;
};

export type PageFaqFaqListFilter = {
  question?: StringFilter | null | undefined;
  answer?: StringFilter | null | undefined;
};

export type PageFaqFilter = {
  sectionTitle?: StringFilter | null | undefined;
  sectionSubtitle?: StringFilter | null | undefined;
  faqList?: PageFaqFaqListFilter | null | undefined;
};

export type BooleanFilter = {
  eq?: boolean | null | undefined;
  exists?: boolean | null | undefined;
};

export type PageEventsFormFieldsInputFieldFilter = {
  label?: StringFilter | null | undefined;
  fieldType?: StringFilter | null | undefined;
  placeholder?: StringFilter | null | undefined;
  required?: BooleanFilter | null | undefined;
};

export type PageEventsFormFieldsSelectFieldFilter = {
  label?: StringFilter | null | undefined;
  options?: StringFilter | null | undefined;
  required?: BooleanFilter | null | undefined;
};

export type PageEventsFormFieldsTextareaFieldFilter = {
  label?: StringFilter | null | undefined;
  placeholder?: StringFilter | null | undefined;
  required?: BooleanFilter | null | undefined;
};

export type PageEventsFormFieldsFilter = {
  inputField?: PageEventsFormFieldsInputFieldFilter | null | undefined;
  selectField?: PageEventsFormFieldsSelectFieldFilter | null | undefined;
  textareaField?: PageEventsFormFieldsTextareaFieldFilter | null | undefined;
};

export type PageEventsFormOptionsFilter = {
  submitButtonText?: StringFilter | null | undefined;
};

export type PageEventsFilter = {
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  showForm?: BooleanFilter | null | undefined;
  formFields?: PageEventsFormFieldsFilter | null | undefined;
  formOptions?: PageEventsFormOptionsFilter | null | undefined;
};

export type PageSiteAddressFilter = {
  locality?: StringFilter | null | undefined;
  region?: StringFilter | null | undefined;
  country?: StringFilter | null | undefined;
};

export type NumberFilter = {
  lt?: number | null | undefined;
  lte?: number | null | undefined;
  gte?: number | null | undefined;
  gt?: number | null | undefined;
  eq?: number | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<number | null | undefined> | null | undefined;
};

export type PageSiteGeoFilter = {
  latitude?: NumberFilter | null | undefined;
  longitude?: NumberFilter | null | undefined;
};

export type PageSiteOpeningHoursFilter = {
  opens?: StringFilter | null | undefined;
  closes?: StringFilter | null | undefined;
};

export type PageSiteFilter = {
  studioName?: StringFilter | null | undefined;
  stylistName?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  keywords?: StringFilter | null | undefined;
  email?: StringFilter | null | undefined;
  phone?: StringFilter | null | undefined;
  instagramHandle?: StringFilter | null | undefined;
  locationDisplay?: StringFilter | null | undefined;
  calUsername?: StringFilter | null | undefined;
  calDefaultSlug?: StringFilter | null | undefined;
  address?: PageSiteAddressFilter | null | undefined;
  geo?: PageSiteGeoFilter | null | undefined;
  areaServed?: StringFilter | null | undefined;
  openingDays?: StringFilter | null | undefined;
  openingHours?: PageSiteOpeningHoursFilter | null | undefined;
  priceRange?: StringFilter | null | undefined;
};

export type PageFilter = {
  hero?: PageHeroFilter | null | undefined;
  services?: PageServicesFilter | null | undefined;
  portfolio?: PagePortfolioFilter | null | undefined;
  faq?: PageFaqFilter | null | undefined;
  events?: PageEventsFilter | null | undefined;
  site?: PageSiteFilter | null | undefined;
};

export type PagePartsFragment = { __typename: 'Page', hero: { __typename: 'PageHero', badge: string | null, headline: string, subheading: string | null, availabilityNotice: string } | null, services: { __typename: 'PageServices', sectionTitle: string | null, pricingNote: string | null, servicesList: Array<{ __typename: 'PageServicesServicesList', name: string, price: string, duration: string | null, description: string | null, deliverables: Array<string | null> | null, id: string, calSlug: string | null, examples: Array<{ __typename: 'PageServicesServicesListExamples', image: string | null, styleLabel: string | null, alt: string | null } | null> | null } | null> | null } | null, portfolio: { __typename: 'PagePortfolio', heroImage: string | null, ogImage: string | null, ogImageAlt: string | null, portfolioList: Array<{ __typename: 'PagePortfolioPortfolioList', title: string | null, id: string, image: string, alt: string, tag: string | null, images: Array<string | null> | null } | null> | null } | null, faq: { __typename: 'PageFaq', sectionTitle: string | null, sectionSubtitle: string | null, faqList: Array<{ __typename: 'PageFaqFaqList', question: string, answer: string } | null> | null } | null, events: { __typename: 'PageEvents', title: string | null, description: string | null, showForm: boolean | null, formFields: Array<
      | { __typename: 'PageEventsFormFieldsInputField', label: string, fieldType: string | null, placeholder: string | null, required: boolean | null }
      | { __typename: 'PageEventsFormFieldsSelectField', label: string, options: Array<string | null> | null, required: boolean | null }
      | { __typename: 'PageEventsFormFieldsTextareaField', label: string, placeholder: string | null, required: boolean | null }
     | null> | null, formOptions: { __typename: 'PageEventsFormOptions', submitButtonText: string | null } | null } | null, site: { __typename: 'PageSite', studioName: string, stylistName: string, title: string | null, description: string | null, keywords: Array<string | null> | null, email: string | null, phone: string | null, instagramHandle: string | null, locationDisplay: string | null, calUsername: string | null, calDefaultSlug: string | null, areaServed: Array<string | null> | null, openingDays: Array<string | null> | null, priceRange: string | null, address: { __typename: 'PageSiteAddress', locality: string | null, region: string | null, country: string | null } | null, geo: { __typename: 'PageSiteGeo', latitude: number | null, longitude: number | null } | null, openingHours: { __typename: 'PageSiteOpeningHours', opens: string | null, closes: string | null } | null } | null };

export type PageQueryVariables = Exact<{
  relativePath: string;
}>;


export type PageQuery = { page: { __typename: 'Page', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero: { __typename: 'PageHero', badge: string | null, headline: string, subheading: string | null, availabilityNotice: string } | null, services: { __typename: 'PageServices', sectionTitle: string | null, pricingNote: string | null, servicesList: Array<{ __typename: 'PageServicesServicesList', name: string, price: string, duration: string | null, description: string | null, deliverables: Array<string | null> | null, id: string, calSlug: string | null, examples: Array<{ __typename: 'PageServicesServicesListExamples', image: string | null, styleLabel: string | null, alt: string | null } | null> | null } | null> | null } | null, portfolio: { __typename: 'PagePortfolio', heroImage: string | null, ogImage: string | null, ogImageAlt: string | null, portfolioList: Array<{ __typename: 'PagePortfolioPortfolioList', title: string | null, id: string, image: string, alt: string, tag: string | null, images: Array<string | null> | null } | null> | null } | null, faq: { __typename: 'PageFaq', sectionTitle: string | null, sectionSubtitle: string | null, faqList: Array<{ __typename: 'PageFaqFaqList', question: string, answer: string } | null> | null } | null, events: { __typename: 'PageEvents', title: string | null, description: string | null, showForm: boolean | null, formFields: Array<
        | { __typename: 'PageEventsFormFieldsInputField', label: string, fieldType: string | null, placeholder: string | null, required: boolean | null }
        | { __typename: 'PageEventsFormFieldsSelectField', label: string, options: Array<string | null> | null, required: boolean | null }
        | { __typename: 'PageEventsFormFieldsTextareaField', label: string, placeholder: string | null, required: boolean | null }
       | null> | null, formOptions: { __typename: 'PageEventsFormOptions', submitButtonText: string | null } | null } | null, site: { __typename: 'PageSite', studioName: string, stylistName: string, title: string | null, description: string | null, keywords: Array<string | null> | null, email: string | null, phone: string | null, instagramHandle: string | null, locationDisplay: string | null, calUsername: string | null, calDefaultSlug: string | null, areaServed: Array<string | null> | null, openingDays: Array<string | null> | null, priceRange: string | null, address: { __typename: 'PageSiteAddress', locality: string | null, region: string | null, country: string | null } | null, geo: { __typename: 'PageSiteGeo', latitude: number | null, longitude: number | null } | null, openingHours: { __typename: 'PageSiteOpeningHours', opens: string | null, closes: string | null } | null } | null } };

export type PageConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PageFilter | null | undefined;
}>;


export type PageConnectionQuery = { pageConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Page', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero: { __typename: 'PageHero', badge: string | null, headline: string, subheading: string | null, availabilityNotice: string } | null, services: { __typename: 'PageServices', sectionTitle: string | null, pricingNote: string | null, servicesList: Array<{ __typename: 'PageServicesServicesList', name: string, price: string, duration: string | null, description: string | null, deliverables: Array<string | null> | null, id: string, calSlug: string | null, examples: Array<{ __typename: 'PageServicesServicesListExamples', image: string | null, styleLabel: string | null, alt: string | null } | null> | null } | null> | null } | null, portfolio: { __typename: 'PagePortfolio', heroImage: string | null, ogImage: string | null, ogImageAlt: string | null, portfolioList: Array<{ __typename: 'PagePortfolioPortfolioList', title: string | null, id: string, image: string, alt: string, tag: string | null, images: Array<string | null> | null } | null> | null } | null, faq: { __typename: 'PageFaq', sectionTitle: string | null, sectionSubtitle: string | null, faqList: Array<{ __typename: 'PageFaqFaqList', question: string, answer: string } | null> | null } | null, events: { __typename: 'PageEvents', title: string | null, description: string | null, showForm: boolean | null, formFields: Array<
            | { __typename: 'PageEventsFormFieldsInputField', label: string, fieldType: string | null, placeholder: string | null, required: boolean | null }
            | { __typename: 'PageEventsFormFieldsSelectField', label: string, options: Array<string | null> | null, required: boolean | null }
            | { __typename: 'PageEventsFormFieldsTextareaField', label: string, placeholder: string | null, required: boolean | null }
           | null> | null, formOptions: { __typename: 'PageEventsFormOptions', submitButtonText: string | null } | null } | null, site: { __typename: 'PageSite', studioName: string, stylistName: string, title: string | null, description: string | null, keywords: Array<string | null> | null, email: string | null, phone: string | null, instagramHandle: string | null, locationDisplay: string | null, calUsername: string | null, calDefaultSlug: string | null, areaServed: Array<string | null> | null, openingDays: Array<string | null> | null, priceRange: string | null, address: { __typename: 'PageSiteAddress', locality: string | null, region: string | null, country: string | null } | null, geo: { __typename: 'PageSiteGeo', latitude: number | null, longitude: number | null } | null, openingHours: { __typename: 'PageSiteOpeningHours', opens: string | null, closes: string | null } | null } | null } | null } | null> | null } };

export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  hero {
    __typename
    badge
    headline
    subheading
    availabilityNotice
  }
  services {
    __typename
    sectionTitle
    pricingNote
    servicesList {
      __typename
      name
      price
      duration
      description
      deliverables
      examples {
        __typename
        image
        styleLabel
        alt
      }
      id
      calSlug
    }
  }
  portfolio {
    __typename
    heroImage
    ogImage
    ogImageAlt
    portfolioList {
      __typename
      title
      id
      image
      alt
      tag
      images
    }
  }
  faq {
    __typename
    sectionTitle
    sectionSubtitle
    faqList {
      __typename
      question
      answer
    }
  }
  events {
    __typename
    title
    description
    showForm
    formFields {
      __typename
      ... on PageEventsFormFieldsInputField {
        label
        fieldType
        placeholder
        required
      }
      ... on PageEventsFormFieldsSelectField {
        label
        options
        required
      }
      ... on PageEventsFormFieldsTextareaField {
        label
        placeholder
        required
      }
    }
    formOptions {
      __typename
      submitButtonText
    }
  }
  site {
    __typename
    studioName
    stylistName
    title
    description
    keywords
    email
    phone
    instagramHandle
    locationDisplay
    calUsername
    calDefaultSlug
    address {
      __typename
      locality
      region
      country
    }
    geo {
      __typename
      latitude
      longitude
    }
    areaServed
    openingDays
    openingHours {
      __typename
      opens
      closes
    }
    priceRange
  }
}
    `;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  